---
application_template:
  auto_deploy: true
  context: release-handsup-us-east-1
  domain: releaseapp.gethandsup.com
  repo_name: draiken/apache-php
  hostnames:
    - web: web-apache-php-${env_id}.${domain}
  environment_templates:
    - name: ephemeral
    - name: permanent
  resources:
    cpu:
      limits: 1000m
      requests: 100m
    memory:
      limits: 1Gi
      requests: 100Mi
    replicas: 1
  services:
    - name: web
      image: draiken/apache-php/web
      build:
        context: app
      has_repo: true
      volumes: []
      ports:
        - type: node_port
          target_port: "80"
          port: "80"
          loadbalancer: false
  workflows:
    - name: setup
      parallelize:
        - step: services-0
          tasks:
            - services.web
    - name: patch
      parallelize:
        - step: services-0
          tasks:
            - services.web
    - name: teardown
      parallelize:
        - step: remove-environment
          tasks:
            - release.remove_environment
